# Install the course conda environment by running 
# the following command in your conda base environment:
# (base)> conda env create -f environment.yml
# After installing the environment, you can activate it using:
# (base)> conda activate churn_pred_env

name: 'churn_pred_env'
channels:
  - conda-forge
  - defaults
dependencies:
  - jinja2
  - python-graphviz
  - lightgbm
  - xgboost
  - graphviz
  - ipykernel
  - scikit-learn[version='==1.1.3']
  - matplotlib[version='>=3.2.2']
  - requests[version='>=2.24.0']
  - pandas[version='>=1.3.*']
  - altair_saver
  - docopt
  - seaborn
  - vl-convert-python
  - yellowbrick
  - ipywidgets
  - pandoc[version>='2.19.*']
  - yacs
  - shap
  - pip